name: Compile
on:
  push:
    branches: [ master ]
    paths: [ 'exercises.tex' ]
  pull_request:
    branches: [ master ]
    paths: [ 'exercises.tex' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile Document
        uses: dante-ev/latex-action@v0.2.0
        with:
          root_file: exercises.tex
          args: -lualatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
      - name: Upload Compiled Document
        uses: actions/upload-artifact@v2
        with:
          name: Exercises
          path: exercises.pdf
